### ISSUE TITLE
Gradle 4.3+ incompatibility with ExportsConfigRules

### ISSUE THREAD

**Issue by big-guy** [wpilibsuite/native-utils#4]
In Gradle 4.3, some of the properties for the compilation and link tasks changed:
https://docs.gradle.org/current/release-notes.html#changes-to-incubating-native-compile-and-link-tasks

This was done to support some improvements we're working on to add proper dependency management, build cache support and simplify the plugin programming model in the native domain.

This was raised as an issue at https://github.com/gradle/gradle/issues/3413.

The type of `objDir` was `File` and now it's `DirectoryProperty`.  This was relying on the toString representation to be the absolute path. For `DirectoryProperty`, the toString is `value: D:\allwpilib\hal\build\objs\halSim\shared\halSimCpp`.

Here's where `objDir` is defined:
https://github.com/wpilibsuite/native-utils/blob/master/src/main/groovy/edu/wpi/first/nativeutils/rules/ExportsConfigRules.groovy#L49

The quick and dirty fix is to call `it.objectFileDir.get().getAsFile()`, this will give you a `File` as before, but tie your plugins to Gradle 4.3+.

If I understand what you're doing in the plugin, I would suggest a few other things:
1. It looks like generating the exports file should be a task of its own.  Then you can wire compile <- export generator <- link and get some incremental goodness from it.  You can find some more information about writing custom Gradle tasks in our [Gradle Guides](https://guides.gradle.org/implementing-gradle-plugins/) and how the new Provider types fit into things. Gradle 4.4 docs will include more information about this.
1. I think it doesn't matter where the exports file is written, so you may consider just putting it in your own path (then you don't need to reach into the compile task).
1. I don't know if you've noticed some of the [new native work](https://github.com/gradle/gradle-native) we're doing now.  There are some [simple samples](https://github.com/gradle/native-samples) you can look at. We would love to hear about any particular use cases you'd like Gradle to support as issues on the gradle-native board.

HTH

**Comment by ThadHouse** [comment]
Thanks for the issue @big-guy 

I will definitely look into splitting the tasks up. As long as we can still read from the object file directory and get a filetree from it, since we do pass it to another object. If we can get some better incremental support by splitting the tasks, that probably is a better thing to do.

For 2, we can definitely put it anywhere, it just seemed like there was a decent place since we already had to read from the directory. But we can then move it.

For 3, I've taken a look at it. We have a few big things we need to support before we can look into moving to the new native work. One of the big things I've noticed wasn't possible is we need to publish both shared and static archives of dependencies, and have different components link to dependencies either shared or statically depending on the configuration of the component. Looking at the examples, I could not find a way to make this work. The other big thing we do is we have to be able to support cross platform builds, and scenarios where we are actually cross compiling a binary. And because of our customers, this has to occur with no configuration. It just has to work, or we get major complaints. Because of this, any publishing actually needs to be tagged with the architecture it was built with, and we need to be able to grab those dependencies from maven. I would be happy to discuss more of our edge cases and requirements, because they are definitely on the odd side of things. 

Note we have actually determined that through the next season (This project is actually for competition robots, and the season runs from january through march) that we will be keeping with gradle 4.1, as we want to make sure nothing breaks.

**Comment by ThadHouse** [comment]
In case it wasn't clear, what that exports function does is it actually reads all the individual object files, and passes them through a generator that generate all the exports that we want exposed. It then passes all the exports to the linker. So we definitely need to be able to get directories to all the object files, but it only has to work on windows.

**Comment by big-guy** [comment]
Great, if you have any questions, feel free to ask them on https://discuss.gradle.org/

> One of the big things I've noticed wasn't possible is we need to publish both shared and static archives of dependencies, and have different components link to dependencies either shared or statically depending on the configuration of the component.

Yep, this is on our roadmap. Being able to build them and then being able to depend on them: https://github.com/gradle/gradle-native/issues/160

>  The other big thing we do is we have to be able to support cross platform builds, and scenarios where we are actually cross compiling a binary. 

Cross-compilation is a little further out, but adding the platform information into the publications is ~next our list.  We're doing design work now for it.

**Comment by ThadHouse** [comment]
We've bumped everything and this has been solved for a long time, So I'm going to close it.
